-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.user_roles
(
    id serial,
    user_role character varying(40) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_user_role UNIQUE (user_role)
);

CREATE TABLE IF NOT EXISTS public.booking_states
(
    id serial,
    booking_state character varying(40) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_booking_state UNIQUE (booking_state)
);

CREATE TABLE IF NOT EXISTS public.payment_types
(
    id serial,
    payment_type character varying(60) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_payment_types UNIQUE (payment_type)
);

CREATE TABLE IF NOT EXISTS public.hotel
(
    id serial,
    hotel_name character varying(100) NOT NULL,
    maximun_free_calendar_days integer NOT NULL DEFAULT 30,
    check_in_hour_time time without time zone NOT NULL,
    check_out_hour_time time without time zone NOT NULL,
    minimal_prev_days_to_cancel integer NOT NULL DEFAULT 5,
    iana_time_zone character varying(60) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_hotel_name UNIQUE (hotel_name)
);

CREATE TABLE IF NOT EXISTS public.admins
(
    id serial,
    user_role integer NOT NULL,
    admin_name character varying(100) NOT NULL,
    admin_description character varying(150),
    hash_password text NOT NULL,
    reset_token text,
    created_at timestamp without time zone DEFAULT now(),
    email character varying(80) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_admin_name UNIQUE (admin_name),
    CONSTRAINT unique_admin_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.clients
(
    id serial,
    user_role integer NOT NULL,
    client_name character varying(60) NOT NULL,
    client_last_name character varying(60) NOT NULL,
    hash_password text,
    email character varying(120),
    reset_token text,
    created_at timestamp without time zone DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT unique_email UNIQUE (email)
);

COMMENT ON COLUMN public.clients.hash_password
    IS 'A client record can be created by a real client, wish requires a pasword to be hashed and stored here, or by a hotel admin, wish not need to create a pasword for the client, just name and last name, so this field is optional.';

COMMENT ON COLUMN public.clients.email
    IS 'Optional too since clients created by and hotel admin does not require email field';

CREATE TABLE IF NOT EXISTS public.room_amenity
(
    id serial,
    amenity character varying(100) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_amenity UNIQUE (amenity)
);

CREATE TABLE IF NOT EXISTS public.room
(
    id serial,
    hotel_id integer NOT NULL,
    room_name character varying(20) NOT NULL,
    night_price numeric NOT NULL,
    capacity integer NOT NULL,
    number_of_beds integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    room_type integer,
    PRIMARY KEY (id),
    CONSTRAINT unique_room_name UNIQUE (room_name)
);

CREATE TABLE IF NOT EXISTS public.rooms_amenities
(
    room_id integer,
    amenity_id integer,
    CONSTRAINT id PRIMARY KEY (room_id, amenity_id),
    CONSTRAINT amenity_id_unique UNIQUE (amenity_id)
);

CREATE TABLE IF NOT EXISTS public.room_pictures
(
    id serial,
    room_id integer NOT NULL,
    filename text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.booking
(
    id serial,
    client_id integer,
    booking_state integer,
    payment_type integer,
    currency integer,
    total_price numeric NOT NULL,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL,
    number_of_guests integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.currencies
(
    id serial,
    currency character varying(10) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_currency UNIQUE (currency)
);

CREATE TABLE IF NOT EXISTS public.rooms_bookings
(
    id serial,
    room_id integer,
    booking_id integer,
    PRIMARY KEY (id)
);
-- TODO evalutate the posibility of set if not yet room_id unique 

CREATE TABLE IF NOT EXISTS public.room_lock_period
(
    id serial,
    room_id integer,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL,
    reason character varying(300) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.room_types
(
    id serial,
    room_type character varying(30) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unque_room_type UNIQUE (room_type)
);

ALTER TABLE IF EXISTS public.admins
    ADD CONSTRAINT user_role FOREIGN KEY (user_role)
    REFERENCES public.user_roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.clients
    ADD CONSTRAINT user_role FOREIGN KEY (user_role)
    REFERENCES public.user_roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.room
    ADD CONSTRAINT hotel_id FOREIGN KEY (hotel_id)
    REFERENCES public.hotel (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.room
    ADD FOREIGN KEY (room_type)
    REFERENCES public.room_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rooms_amenities
    ADD CONSTRAINT room_id_link FOREIGN KEY (room_id)
    REFERENCES public.room (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rooms_amenities
    ADD CONSTRAINT amenity_id_link FOREIGN KEY (amenity_id)
    REFERENCES public.room_amenity (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.room_pictures
    ADD CONSTRAINT room_link FOREIGN KEY (room_id)
    REFERENCES public.room (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.booking
    ADD CONSTRAINT client_link FOREIGN KEY (client_id)
    REFERENCES public.clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.booking
    ADD CONSTRAINT booking_state_link FOREIGN KEY (booking_state)
    REFERENCES public.booking_states (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.booking
    ADD CONSTRAINT payment_type_link FOREIGN KEY (payment_type)
    REFERENCES public.payment_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.booking
    ADD CONSTRAINT currency_link FOREIGN KEY (currency)
    REFERENCES public.currencies (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rooms_bookings
    ADD CONSTRAINT booking_link FOREIGN KEY (booking_id)
    REFERENCES public.booking (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rooms_bookings
    ADD CONSTRAINT room_link FOREIGN KEY (room_id)
    REFERENCES public.room (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.room_lock_period
    ADD CONSTRAINT room_link FOREIGN KEY (room_id)
    REFERENCES public.room (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;